[package]
name = "sample_gnuplot"
version = "0.1.0"
authors = ["Syata Kurasi <soccer_Rs0515@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gnuplot = "0.0.32"
nalgebra = "0.27.1"
